import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
// This test mutates ONLY the separate local server on port 5174.
const root='http://127.0.0.1:5174';
async function call(body,admin=false){const r=await fetch(root+'/api/contest',{method:'POST',headers:{'Content-Type':'application/json',Origin:root,...(admin?{'oai-authenticated-user-id':'test-admin','oai-authenticated-user-email':'seedy@sites.test'}:{})},body:JSON.stringify(body)});return {status:r.status,data:await r.json()}}
const get=async()=>await(await fetch(root+'/api/contest')).json();
let s=await get();assert.equal(s.state,'draft');assert.equal(s.entries.length,6);
assert.equal((await call({action:'open'})).status,403);
const team='Best Team/Group Costume',creative='Most Creative/Original',funny='Funniest';
const voterA=crypto.randomUUID(),voterB=crypto.randomUUID(),voterC=crypto.randomUUID();
assert.equal((await call({action:'vote',voter:voterA,category:team,entry:'sample-ghosts'})).status,400);
const form=new FormData();form.set('file',new Blob([readFileSync('public/contestants.png')],{type:'image/png'}),'sample.png');
const upload=await fetch(root+'/api/contest',{method:'POST',headers:{Origin:root,'oai-authenticated-user-id':'test-admin','oai-authenticated-user-email':'seedy@sites.test'},body:form});assert.equal(upload.status,200);const image=(await upload.json()).image;
assert.equal((await fetch(root+'/api/image/'+image)).status,404);
const entry={id:crypto.randomUUID(),name:'Upload Test',costume:'QA Ghost',category:funny,description:'Local test only',tagline:'Testing the afterlife.',image,published:false};
assert.equal((await call({action:'save',entry},true)).status,200);
assert.ok(!(await get()).entries.some(e=>e.id===entry.id));
assert.equal((await call({action:'save',entry:{...entry,published:true}},true)).status,200);
assert.equal((await fetch(root+'/api/image/'+image)).status,200);
assert.equal((await call({action:'open'},true)).status,200);
assert.equal((await call({action:'vote',voter:'INVALID-VOTER',category:team,entry:'sample-ghosts'})).status,400);
assert.equal((await call({action:'vote',voter:voterA,category:funny,entry:'sample-ghosts'})).status,400);
const parallel=await Promise.all(Array.from({length:8},()=>call({action:'vote',voter:voterA,category:team,entry:'sample-ghosts'})));assert.equal(parallel.filter(r=>r.status===200).length,1);assert.equal(parallel.filter(r=>r.status===409).length,7);
assert.equal((await call({action:'vote',voter:voterB,category:team,entry:'sample-pirates'})).status,200);
assert.equal((await call({action:'vote',voter:voterA,category:creative,entry:'sample-viking'})).status,200);
assert.equal((await call({action:'vote',voter:voterA,category:funny,entry:'sample-coffee'})).status,200);
assert.equal((await call({action:'ballot',voter:voterA})).data.votes.length,3);
assert.equal((await call({action:'save',entry:{...s.entries[0],description:'Roster updated while voting is active.'}},true)).status,200);
assert.equal((await call({action:'draw',category:team},true)).status,400);
assert.equal((await call({action:'close'},true)).status,200);
assert.equal((await call({action:'vote',voter:voterC,category:team,entry:'sample-ghosts'})).status,400);
assert.equal((await call({action:'save',entry:{...s.entries[0],description:'Roster updated while paused.'}},true)).status,200);
assert.equal((await call({action:'open'},true)).status,200);
assert.equal((await call({action:'close'},true)).status,200);
assert.equal((await call({action:'draw',category:team},true)).status,400);
assert.equal((await call({action:'finalize'},true)).status,200);
assert.equal((await call({action:'open'},true)).status,400);
const draws=await Promise.all(Array.from({length:5},()=>call({action:'draw',category:team},true)));const draw=draws[0].data.draw;assert.ok(['sample-ghosts','sample-pirates'].includes(draw.winner));assert.equal(JSON.parse(draw.tied).length,2);for(const r of draws)assert.deepEqual(r.data.draw,draw);
s=await get();assert.equal(s.state,'closed');assert.deepEqual(s.draws[0],draw);assert.equal(s.standings.reduce((n,e)=>n+e.votes,0),4);
assert.equal((await call({action:'reset'},true)).status,200);
s=await get();assert.equal(s.state,'draft');assert.equal(s.standings.reduce((n,e)=>n+e.votes,0),0);assert.ok(s.entries.length>=6);
const cross=await fetch(root+'/api/contest',{method:'POST',headers:{Origin:'https://other.example','Content-Type':'application/json'},body:JSON.stringify({action:'vote',voter:voterC,category:team,entry:'sample-ghosts'})});assert.equal(cross.status,403);
console.log('PASS: private uploads, draft approval, published images, samples, organizer authorization, code-free browser voting, active-voting roster edits, pause-edit-resume, finalization, reset, 3-category ballots, 5 concurrent permanent draws, totals, and cross-origin rejection.');
