// Original 100 suggestions recovered from “Build offline Halloween contest app” (September 25, 2026).
export const suggestedTaglines = [
  "Bunker sweet bunker. Please wipe your feet.",
  "Our mission statement survived. Nobody knows why.",
  "The machines run the world. I run the snack committee.",
  "Post-apocalyptic, pre-coffee.",
  "My promotion came with a firmware update.",
  "Dress for the bunker you want.",
  "Living the dream. Downloading the nightmare.",
  "Fully charged and barely engaged.",
  "Corporate survivor with transferable scavenging skills.",
  "Putting the “rust” in trust exercises.",
  "Our quarterly forecast calls for scattered robots.",
  "I brought exceptional references and three spare fuses.",
  "My benefits package includes filtered air.",
  "Proud recipient of the Perfect Survival Attendance Award.",
  "The office thermostat has declared independence.",
  "Our robot overlord has an open-door charging policy.",
  "Another beautiful day in the industrial remains.",
  "The machines can have Earth. This mug is mine.",
  "Rebuilding civilization requires a purchase order.",
  "My title is Senior Director of Finding Working Outlets.",
  "We’ve reached peak efficiency. Nobody’s left to complain.",
  "The AI takeover really streamlined the holiday party.",
  "This wasteland has excellent growth potential.",
  "Bunker morale is up. Oxygen is a separate dashboard.",
  "I’m not obsolete. I’m a heritage employee.",
  "Please allow three to five business eras for a response.",
  "Our disaster recovery plan needs disaster recovery.",
  "The robots offered unlimited PTO. There’s nowhere to go.",
  "My desk survived three uprisings and one office move.",
  "Chief Executive Organic.",
  "Delivering results in a challenging planetary environment.",
  "Please attach receipts for all salvaged equipment.",
  "The robots have taken everything except accountability.",
  "This could’ve been a distress signal.",
  "Last known location: the snack drawer.",
  "I survived the singularity for this?",
  "Our new corporate ladder is an escape hatch.",
  "Don’t talk to me until I’ve had my electrolytes.",
  "My skill set is Excel, adaptability, and water purification.",
  "Even rogue AI wants the weekend off.",
  "Current status: operational, with complaints.",
  "A little rust adds executive presence.",
  "My team is lean. Mostly titanium.",
  "The machines call it optimization. I call it more work.",
  "Our office relocation got a little out of hand.",
  "Humanity’s final deliverable is due Friday.",
  "Outlasting civilization was not in my job description.",
  "My standing desk is now a lookout tower.",
  "We put the “scrap” in scrappy startup.",
  "Brought a casserole to the robot uprising. Networking matters.",
  "The only thing more durable than robots is office gossip.",
  "Our AI overlord still says, “Quick question.”",
  "My password expired before civilization did.",
  "Please keep all existential dread in the designated channel.",
  "We’re a family here. A small, rechargeable family.",
  "Survived on grit, wit, and emergency biscuit.",
  "Just trying to leave this planet with a good reference.",
  "Our company retreat became a permanent retreat.",
  "My robot replacement asked me to train its replacement.",
  "Bunker capacity: twelve people and one very large ego.",
  "Humanity 2.0 still needs a lunch break.",
  "The future called. It needs an adapter.",
  "I joined the resistance for the dental plan.",
  "Our last working scanner only recognizes snacks.",
  "Making the wasteland a better place to work.",
  "Yes, I have apocalypse experience. It’s on page two.",
  "We’re taking a phased approach to restoring sunlight.",
  "Corporate sent drones. We asked for donuts.",
  "I prefer my overlords with a snooze button.",
  "The apocalypse has been added to the risk register.",
  "Please reserve the escape pod through the shared calendar.",
  "My personal brand is mildly radioactive enthusiasm.",
  "Robots never sleep. Apparently, that’s our new benchmark.",
  "Saving humanity one “Undo” at a time.",
  "The bunker has hot desks. The cooling system failed.",
  "Our team-building exercise is locating the team.",
  "I’m the reason the robots added a patience setting.",
  "The machines conquered Earth and immediately scheduled training.",
  "My annual goals include remaining carbon-based.",
  "Our office view is now technically open concept.",
  "Surviving the end times with beginning-of-week energy.",
  "The robot uprising had better presentation slides.",
  "I’m essential personnel. I brought the can opener.",
  "Please stop using the emergency beacon to order lunch.",
  "My PTO request is older than the wasteland.",
  "Our last human tradition is blaming the previous shift.",
  "They automated everything except the awkward icebreakers.",
  "I asked for a corner office. They gave me a bunker elbow.",
  "Planet rebooting. Please enjoy this hold music.",
  "Our new dress code is business combustible.",
  "I survived the machine age with Stone Age troubleshooting.",
  "The robots respect me for my extensive cable collection.",
  "Earth is under new management. The logo looks expensive.",
  "Bringing a human touch to a touchless civilization.",
  "My retirement plan is a fully charged escape scooter.",
  "Today’s agenda: water, shelter, font selection.",
  "Our culture committee has become a survival committee.",
  "If found, please return to the nearest functioning break room.",
  "The world ended, but somebody still microwaved fish.",
  "Built to survive. Available for promotion."
] as const;

export function suggestTagline(current: string): string {
  const choices = suggestedTaglines.filter(tagline => tagline !== current);
  return choices[Math.floor(Math.random() * choices.length)];
}
